### ISSUE TITLE
404 Error on newest version

### ISSUE THREAD

**Issue by joshali1990** [mdhiggins/PlexAutoSkip#39]
Hello,

I have been getting the follow error on the latest version: 

INFO - Seeking Plex for Android (TV) player playing 39 [48494] (The Simpsons s25e18 - Days of Future Future) AFTR|e40252f9598ac079-com-plexapp-android from 1303052 to 1330061
ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "/Users/joshali/PlexAutoSkip-master/resources/skipper.py", line 229, in _seekTo
    self.seekPlayerTo(mediaWrapper.player, mediaWrapper, targetOffset)
  File "/Users/joshali/PlexAutoSkip-master/resources/skipper.py", line 255, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "/Users/joshali/PlexAutoSkip-master/resources/mediaWrapper.py", line 346, in seekTo
    player.seekTo(offset)
  File "/opt/homebrew/lib/python3.10/site-packages/plexapi/client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/opt/homebrew/lib/python3.10/site-packages/plexapi/client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "/opt/homebrew/lib/python3.10/site-packages/plexapi/server.py", line 753, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; https://192-168-68-152.92110a007d7b460a93c63f8bd7a73073.plex.direct:32400/player/playback/seekTo?commandID=1&offset=1330061&type=video <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>

**Comment by mdhiggins** [comment]
Might need to restart or relog your Android TV client. No changes made to this command and this is a Plex API failure. Try all the steps in troubleshooting for Bad Request

**Comment by DevMan01** [comment]
I don't think @joshali1990 is the only one. I'm getting this error too. This only started happening within the last week or so.

Here's my log:
[PlexAutoSkip_error.log](https://github.com/mdhiggins/PlexAutoSkip/files/10878677/PlexAutoSkip_error.log)

Here's my config.ini (secrets redacted, changed file suffix to .txt for GitHub):
[PlexAutoSkip_error_config.txt](https://github.com/mdhiggins/PlexAutoSkip/files/10878683/PlexAutoSkip_error_config.txt)

Python Version: `~$ python3 --version Python 3.10.6`

Hosted on Linux:
>Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Troubleshooting steps I've tried:

- Double-checked basic settings: GDM/Network, Local network CIDR range, Advertise as Player settings, running on the same subnet.
- Refreshed Plex token.
- Logged out/in
- Switched secure connections from `Required` to `Preferred`.
- Disabled IPv6 on PMS
- Switched PlexAutoSkip config.ini to `ignore-certs = true`
- Completely uninstalled PlexAutoSkip, and re-installed

**Comment by mdhiggins** [comment]
Still think this is a Plex problem, I pulled the latest PAS container and latest Plex server and everything is working fine on my end. I also haven't made any recent changes to this and the script is only failing at the actually API command going to the player which means its down to the API. The only real way to get the 404 error is a problem with Plex Companion not reporting itself to the server correctly, a security problem, or companion problem

https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/

Check this info here and see if any of these suggestions help, most importantly seeing if your client that's giving you trouble is showing up on the client list

`http://server.local.ip.address:32400/clients`

I would also check and see if the client APIs for companion are working, which you can see if you get a valid XML return with

`http://clientip:32500/resources?token=<PLEXTOKEN>`

You can also potentially get the error if your HTTPS certificate is expired or invalid, can try setting to Server Settings > Network > Secure Connections to "Preferred" instead of Required

Let me know how that stuff goes and feel free to share info

Does rolling back to an older version of PAS resolve the issue?

In the mean time I'll put an update out that allows the fallback approach I use for BadRequests also apply to this NotFound error as a workaround but you shouldn't need this approach on an otherwise working GDM setup

**Comment by mdhiggins** [comment]
cfea592527bfd3a0d13aed7a34a63ddae930b123

For reference, a valid XML client return should look something like this

```xml
<MediaContainer>
<Player platformVersion="11.5.0 build 4312" protocolVersion="1" machineIdentifier="CENSORED" deviceClass="stb" platform="Roku" version="7.0.23.8111-8c8a6a9b7-Plex" protocolCapabilities="timeline,playback,playqueues" title="Living Room" product="Plex for Roku"/>
</MediaContainer>
```

If its just empty MediaContainer tags then its invalid

**Comment by mdhiggins** [comment]
@DevMan01 Unlike the Android clients which don't have the option, for Apple TV you also need to enable "Remote Control" in the settings if you haven't done that, I see you mention advertise as player which is essentially the same thing in other apps but I believe on the ATV it isn't called that and that option isn't present, I would double check that as well

**Comment by joshali1990** [comment]
> Still think this is a Plex problem, I pulled the latest PAS container and latest Plex server and everything is working fine on my end. I also haven't made any recent changes to this and the script is only failing at the actually API command going to the player which means its down to the API. The only real way to get the 404 error is a problem with Plex Companion not reporting itself to the server correctly, a security problem, or companion problem
> 
> https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/
> 
> Check this info here and see if any of these suggestions help, most importantly seeing if your client that's giving you trouble is showing up on the client list
> 
> `http://server.local.ip.address:32400/clients`
> 
> I would also check and see if the client APIs for companion are working, which you can see if you get a valid XML return with
> 
> `http://clientip:32500/resources?token=<PLEXTOKEN>`
> 
> You can also potentially get the error if your HTTPS certificate is expired or invalid, can try setting to Server Settings > Network > Secure Connections to "Preferred" instead of Required
> 
> Let me know how that stuff goes and feel free to share info
> 
> Does rolling back to an older version of PAS resolve the issue?
> 
> In the mean time I'll put an update out that allows the fallback approach I use for BadRequests also apply to this NotFound error as a workaround but you shouldn't need this approach on an otherwise working GDM setup

I get 401 unauthorized when trying to view the clients xml. Tried restarting my Plex server and it's the same thing

**Comment by mdhiggins** [comment]
So the client list doesn't work or the client resources page doesn't work?

Are secure connections required? Did turning that off to Preferred have any impact if so?

**Comment by joshali1990** [comment]
Client list. Secure connections is set to preferred.

**Comment by joshali1990** [comment]
Newest version works. I have another weird issue. On my apple tv after there is an autoskip the next time a file plays my server connection is listed as transient. This isn't an issue for most files, but if the file is in a different directory than the previous one then it will not load for some reason. Not sure what could be causing that.

**Comment by mdhiggins** [comment]
Newest version just bypasses proxying through the server and direct controls the player via its IP address. The fact that you're getting the 404 error means there is till something weird going on with your Plex server and GDM isn't working like it should, this may also be to blame for the other issue you're seeing. There is likely some kind of underlying network issue if the client list isn't reporting

Are you using the skip-next feature? The skip next feature works by creating a new play queue and advancing the selected item and then sending that new queue to the player. This new queue, if there is some issues with communicating with the server may not be recognized as coming from the correct IP address if the server is having a hard time showing the server on its client list. If you have some logs from the first and second episodes showcasing the normal behavior and the subsequent "transient" content I can take a look. 

I would try and do some more Plex troubleshooting and see why you can't get your client list to open

You can try adding a token to the client list to see if that changes anything
`http://server.local.ip.address:32400/clients?token=<<token>>`

I would also try clearing out your cache directory for Plex

1. Close the Plex server application so the server isn't running
2. Go to  [Plex Data Directory](https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/)
3. Delete the "Cache" folder
4. Start server again

**Comment by mdhiggins** [comment]
Upon doing some further testing it does look like maybe Plex changed something server side and the scenarios that used to throw the Badrequest error are now throwing the 404 error instead, everything mentioned above still applies but applying the fallback method here does seem to help as anticipated

**Comment by joshali1990** [comment]
Started getting the 404 error even on the newest version (actually looks like you just posted another version, would this change anything?). Still can't get access to the clients xml even with clearing my cache and restarting PMS. As for the transient server thing, I'll have to try capturing some logs later today.

**Comment by mdhiggins** [comment]
New update was just to capture the error message for 404 better but it should direct connect now

**Comment by joshali1990** [comment]
Not sure if you can get anything from these, but I played both with and without Plex auto skip. I did find this error: Mar 03, 2023 13:28:41.421 [0x16b763000] WARN - Auth: Access denied to transient token call with method PUT
[Plex Media Server.log](https://github.com/mdhiggins/PlexAutoSkip/files/10885246/Plex.Media.Server.log)

**Comment by mdhiggins** [comment]
Was actually looking for the PlexAutoSkip logs for when it switches to transient mode from session to session (debug level logs please). I would have to defer to the Plex team to decipher the Plex logs

**Comment by joshali1990** [comment]
[pas.log](https://github.com/mdhiggins/PlexAutoSkip/files/10885276/pas.log)

**Comment by mdhiggins** [comment]
That all looks like its working ok but that's just logs from a single session (session 19). I'm assuming session 20 would be the one that gives you the transient mode issue? I'm wondering if the reported IP address for the client is somehow messed up

Might need verbose logging

set environment variable PAS_VERBOSE=true to get verbose logging and let the logs capture the end of the session and subsequent start of the next session

Also I have a new update that I just pushed that handles the BadRequest/404 errors a little more gracefully by checking to see if the player is in the client list rather than relying on the exceptions to trigger the fallback. This is nice too as its done as soon as the session starts and is preserved for the whole session rather than needing to be regenerated on each request

3059c6692b51fd035d4b0a6aa2f2325e4dabb77b

**Comment by joshali1990** [comment]
Here's another. Where do I set verbose logging? 
[pas.log](https://github.com/mdhiggins/PlexAutoSkip/files/10885364/pas.log)

**Comment by mdhiggins** [comment]
That all looks ok, IP addresses are maintained from session to session so maybe not the issue I was guessing

Its an environment variable so you just need to set it in the same environment before you launch the script 

If you're on a unix based system just run `export PAS_VERBOSE=true` before you open the script in the same terminal window

Also try grabbing the latest update, should at least make those logs look a little cleaner with less exceptions

**Comment by joshali1990** [comment]
[pas.log](https://github.com/mdhiggins/PlexAutoSkip/files/10885403/pas.log)

No idea what could be causing it to go transient after the next play.

**Comment by mdhiggins** [comment]
Yeah I got nothing. And it doesn't do that if you're not using PAS? It's not even making a new play queue or modifying the session it's only seeking so no idea why

**Comment by joshali1990** [comment]
It does not. I assume it has something to do with plexapi though.

**Comment by DevMan01** [comment]
> @DevMan01 Unlike the Android clients which don't have the option, for Apple TV you also need to enable "Remote Control" in the settings if you haven't done that, I see you mention advertise as player which is essentially the same thing in other apps but I believe on the ATV it isn't called that and that option isn't present, I would double check that as well

Correct. I double checked this, it is set correctly.

> Still think this is a Plex problem, I pulled the latest PAS container and latest Plex server and everything is working fine on my end. I also haven't made any recent changes to this and the script is only failing at the actually API command going to the player which means its down to the API. The only real way to get the 404 error is a problem with Plex Companion not reporting itself to the server correctly, a security problem, or companion problem

> https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/

> Check this info here and see if any of these suggestions help, most importantly seeing if your client that's giving you trouble is showing up on the client list
> ...

I was able to successfully complete these two calls. However, I did have to set my PMS -> Network -> Secure Connections to "Preferred", it was denying them flat out in the PMS logs. 

Results:

Call: `https://<PMS Server IP>:32400/clients`
Result:
`
<MediaContainer size="1">
<Server name="Apple TV" host="<REDACTED>" address="<REDACTED>" port="32500" machineIdentifier="<REDACTED>" version="8.15" protocol="plex" product="Plex for Apple TV" deviceClass="stb" protocolVersion="2" protocolCapabilities="playback,playqueues,timeline,provider-playback"/>
</MediaContainer>
`

I was also able to complete the second call: `http://<CLIENT IP>:32500/resources?token=<REDACTED>`
Result:
`
<MediaContainer size="1">
<Player machineIdentifier="<REDACTED>" product="Plex for Apple TV" protocol="plex" deviceClass="stb" platform="tvOS" platformVersion="16.3.2" title="Apple TV" protocolCapabilities="playback,playqueues,timeline,provider-playback" protocolVersion="1"/>
</MediaContainer>
`

After following the thread a bit, I pulled the latest to see if the changes you mentioned, the fallback method, helped. Changes are as follows:


>~/PlexAutoSkip$ git pull
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 9), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (12/12), 1.42 KiB | 132.00 KiB/s, done.
From https://github.com/mdhiggins/PlexAutoSkip
   c0af54d..3059c66  master     -> origin/master
Updating c0af54d..3059c66
Fast-forward
 resources/skipper.py | 37 ++++++++++++++++++++++++++++---------
 1 file changed, 28 insertions(+), 9 deletions(-)


Trying the changes out worked!

>~/PlexAutoSkip$ python3 main.py 
INFO - /usr/bin/python3
INFO - Loading config file /home/devman/PlexAutoSkip/config/config.ini.
INFO - Loading custom JSON file /home/devman/PlexAutoSkip/config/custom.json
INFO - Connecting to Plex server...
INFO - Connected to Plex server DevHood Media Library using plex.tv account
INFO - Skipper initiated and ready
INFO - Websocket connected
INFO - Found new session 33 [56578] (Stranger Things s04e01 - Chapter One: The Hellfire Club) Apple TV|54131A6B-9A53-4ADA-A041-2B85E42AC66A viewOffset 503753 D3vM4n on Plex for Apple TV, sessions: 0
INFO - Found skippable marker intro for media 33 [56578] (Stranger Things s04e01 - Chapter One: The Hellfire Club) Apple TV|54131A6B-9A53-4ADA-A041-2B85E42AC66A with range 528130(+3000)-588140(+1000) and viewOffset 532067
INFO - Seeking Plex for Apple TV player playing 33 [56578] (Stranger Things s04e01 - Chapter One: The Hellfire Club) Apple TV|54131A6B-9A53-4ADA-A041-2B85E42AC66A from 532068 to 589140

Can you help me understand better, why this change made a difference?

**Comment by mdhiggins** [comment]
So ultimately its a Plex problem, certain clients aren't reporting themselves on the client list even though they do report themselves on devices and sessions. As a result, when you go to send commands to them the Plex API, fails because there is no matching device on the client list and the server fails to send the command (since sending commands through the server depends on the client list). The big issue with the 404 error specifically is that the error message and exception type for this problem changed recently with a Plex server update. Previously this same scenario would throw a "BadRequest" error instead of a "NotFound" error

Fortunately, when Plex fails to put the clients on the list there's still enough data from the device and session info for me to get the IP address and port of the client and send the commands directly to the player device bypassing the server. This fallback method wasn't being used because PlexAutoSkip previously only triggered this approach when it encountered a "BadRequest" exception, so the new "NotFound" exception change wasn't accounted for

Rather than rely on the exception to fire now, the new update to PlexAutoSkip just looks at the client list and checks if the player from the current session is present. If not, it doesn't even bother trying to connect through the server now and just goes straight to the direct IP approach thus avoiding this scenario in the future in the event the error type changes again and fixes the issue with "NotFound" and "BadRequest" errors

**Comment by DevMan01** [comment]
Brilliant! Nicely done!!

**Comment by mdhiggins** [comment]
Just pushed one more small update, needed to do some tweaks to checking the clients and some IP address comparisons for some edge cases
