### ISSUE TITLE
Error with latest plex update

### ISSUE THREAD

**Issue by RaaZeR2169** [mdhiggins/PlexAutoSkip#41]
Getting the following error when it wants to skip: 
INFO - Found new session 544 [542655] (Mayor of Kingstown s02e09 - Peace in the Valley) Apple TV|1FD5D7B4-5372-41DD-AA52-D052E776D891 viewOffset 301583 Raazer, sessions: 0
INFO - Found skippable marker intro for media 544 [542655] (Mayor of Kingstown s02e09 - Peace in the Valley) Apple TV|1FD5D7B4-5372-41DD-AA52-D052E776D891 with range 299120-360110 and viewOffset 301584
INFO - Seeking Plex for Apple TV player playing 544 [542655] (Mayor of Kingstown s02e09 - Peace in the Valley) Apple TV|1FD5D7B4-5372-41DD-AA52-D052E776D891 from 301585 to 360110
ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "E:\copy\plexautoskip-master\resources\skipper.py", line 213, in _seekTo
    self.seekPlayerTo(mediaWrapper.player, mediaWrapper, targetOffset)
  File "E:\copy\plexautoskip-master\resources\skipper.py", line 239, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "E:\copy\plexautoskip-master\resources\mediaWrapper.py", line 319, in seekTo
    player.seekTo(offset)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\plexapi\client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\plexapi\client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\plexapi\server.py", line 753, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; https://192.168.1.169:32400/player/playback/seekTo?commandID=1&offset=360110&type=video <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>

**Comment by mdhiggins** [comment]
I don't think you're on the latest version, the error lines don't match up and the logging is missing some recent changes from about 3-4 weeks ago. There's been updates that addresses the 404 error

You'll also get the 404 error if you don't have the remote control feature enabled on your Apple TV if it persists after updating

But I can say for sure you're missing this commit

https://github.com/mdhiggins/PlexAutoSkip/commit/2cd56c3260001c8259a4238735a3ca0cc012eaf1

Since your marker logging doesn't show that change, and all the changes for the 404 fix came after that

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/PlexAutoSkip/issues/39

Probably the same as this issue which is fixed with latest update
